fix: make buttons look like further buttons
pi-top/pi-topOS-Web-Portal pull request #332
Opened 2022-02-03 16:56 UTC by zz-james

ticket: https://pi-top.atlassian.net/browse/OS-1146

replace styled buttons with primary button component from Further, leave unstyled (link) buttons the same.

changed the margin on the dialog too to match design on ticket. 

My editor made some formatting changed, sorry about that - are we all on the same settings, it would be a pain if we kept automatically reformatting each other...

2022-02-04 15:51 UTC, olivierwilkinson requested changes
I've got an off by one issue on Firefox, Safari and Chrome, they are all a little different but the problem seems to be the same:

<img width="355" alt="Screenshot 2022-02-04 at 15 50 02" src="https://user-images.githubusercontent.com/15321261/152559634-e75305e4-2e2c-4009-a188-7a6ef6b3d8ef.png">

2022-02-08 19:55 UTC, zz-james commented
I've improved it (at least in my experience tested mac, win10 and ubuntu) - the outline is very slightly thicker than it was in the original design because the original had a stroke width of 1.8, which caused a bit of, I guess dithering? to approximate something wider than 1 but lass then 2, now it has a solid 2 which improves the situation a lot, especially around the anti-aliasing at the ends of the curves. 

even after extensive refactoring FireFox on mac (but not on Windows or Ubuntu) still was off by  one, so now it has it's own CSS to fix it.

2022-02-09 12:01 UTC, olivierwilkinson commented
I'm finding issues when the font loads in, but before that it looks perfect.
Before font loads in
<img width="186" alt="Screenshot 2022-02-09 at 11 33 30" src="https://user-images.githubusercontent.com/15321261/153196102-6a69e61a-3b9f-40c4-a504-54e5e2961324.png">
After font loads in
<img width="162" alt="Screenshot 2022-02-09 at 11 31 20" src="https://user-images.githubusercontent.com/15321261/153196107-ffd93941-940a-491f-b9e9-d089539d3788.png">

2022-02-09 14:33 UTC, zz-james commented
unhelpfully I wasn't seeing this even using the Roboto font. I've made some changes that might help.

2022-02-09 18:08 UTC, angusjfw commented
this looks perfect on my pi-top screen and in windows if I use 100 or 200% ui scaling. With my regular 175% it's fine too just a little stubbly:
![image](https://user-images.githubusercontent.com/7795213/153262557-ac5967a7-517b-4ffe-8291-088f19ebed79.png)
![image](https://user-images.githubusercontent.com/7795213/153262297-6847e072-9f36-4b82-90a5-2e69222dade6.png)

also there is a snapshot failure

2022-02-09 19:25 UTC, zz-james commented
I've taken a couple of screenshots of Chrome at 175% (by far the stubbliest) you are right it is better in the old code, here's what's happening, this is a screenshot at 175% then zoomed 400% in Gimp

![buttons_zoomed](https://user-images.githubusercontent.com/1120870/153275062-94c116dd-52a5-4686-8227-f32a8737ccb1.png)


I'm finding it difficult to recreate that part where the straight top/bottom is actually 3 px wide with one px being a semi opaque, and if there curves are going to meet the straights without any hair than either the straights need to have this or the curves need to loose their semi-opaque parts... I haven't figured out this level of control.

For now, I am not upset at all to leave the Further buttons how they are, I guess there's pros and cons

2022-02-10 09:12 UTC, zz-james commented
I found a way to control the stubble pixels using a clip-path, surrounding the button with a rect that acts as a mask - this trims the bottom and the top so there's no wayward anti-aliasing - this screenshot is 175% on browser then zoomed to 400
![Screenshot from 2022-02-10 09-06-01](https://user-images.githubusercontent.com/1120870/153374355-0e75aecc-0086-4c61-bc9d-9cd255deae40.png)

I made a few other little changes to make the roll-over fill fit into the shape better 

commit to follow shortly

2022-02-10 13:03 UTC, zz-james commented on node_modules/.yarn-integrity
> +{
uh no idea when that arrived I didn't ask for it. I will remove

2022-02-10 13:04 UTC, zz-james commented on frontend/src/components/atoms/dialog/Dialog.module.css
> +  margin: 0 50px;
oh weird I thought it was needed to make the dialog text like the design, but will remove :-)

2022-02-10 13:58 UTC, angusjfw commented
There's been a bit of back and forth with this isSingleOption ValueType issue that's currently breaking the build.
https://github.com/pi-top/pi-topOS-Web-Portal/commit/13b7e8fc3102f368c3f63caa4ec2eccac79313cc

It seems like maybe this was a breaking change in react-select, between 3.0 and 3.1, without being marked as a major update. You're yarn lock is now resolving to 3.1 again which is why this broke again I think.

Maybe just try bumping react-select to the latest, 5.2.2? Or if that's problematic I suppose just revert this change again.

2022-02-10 14:54 UTC, zz-james commented
ok have replaced the original yarn.lock file from master as there were more problems with react-testing-library building ok now.

2022-02-10 15:08 UTC, merged